import jakarta.servlet.ServletException;
import jakarta.servlet.annotation.WebServlet;
import jakarta.servlet.http.HttpServlet;
import jakarta.servlet.http.HttpServletRequest;
import jakarta.servlet.http.HttpServletResponse;
import java.io.IOException;
import java.sql.*;

/**
 * Servlet implementation class SignUpCrewServlet
 */
@WebServlet("/SignUpCrewServlet")
public class SignUpCrewServlet extends HttpServlet {
    private static final long serialVersionUID = 1L;

    public SignUpCrewServlet() {
        super();
    }

    protected void doPost(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
        // Retrieve input data from the form
        String crewid = request.getParameter("crewid"); // Optional: Can be auto-generated by SQL Server
        String crewfirstname = request.getParameter("crewfirstname");
        String crewlastname = request.getParameter("crewlastname");
        String crewemail = request.getParameter("crewemail");
        String crewphone = request.getParameter("crewphone");
        String crewpassword = request.getParameter("crewpassword"); // Should be hashed for security

        try {
            // Establish SQL Server connection
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            String url = "jdbc:sqlserver://kgjkinserver.database.windows.net:1433;"
                       + "database=kgJkinDB;"
                       + "user=kgjkinadmin@kgjkinserver;"
                       + "password=Mycuties_7;"
                       + "encrypt=true;"
                       + "trustServerCertificate=false;"
                       + "hostNameInCertificate=*.database.windows.net;"
                       + "loginTimeout=30;";
            Connection con = DriverManager.getConnection(url);

            // SQL query to insert the crew member
            String sql = "INSERT INTO CREW (CREWID, CREWFIRSTNAME, CREWLASTNAME, CREWEMAIL, CREWPHONENO, CREWPASSWORD) VALUES (?, ?, ?, ?, ?, ?)";
            PreparedStatement ps = con.prepareStatement(sql);

            // Set the input data into the prepared statement
            ps.setString(1, crewid);  // Manual CREWID (consider making it auto-generated in DB)
            ps.setString(2, crewfirstname);
            ps.setString(3, crewlastname);
            ps.setString(4, crewemail);
            ps.setString(5, crewphone);
            ps.setString(6, crewpassword); // Consider hashing before storing

            // Execute the query
            int rowsInserted = ps.executeUpdate();
            if (rowsInserted > 0) {
                response.sendRedirect("CrewProfile.jsp?id=" + crewid); // Redirect to crew profile
            } else {
                response.getWriter().println("Error: Unable to create the crew account.");
            }

            // Close the connection
            con.close();

        } catch (Exception e) {
            e.printStackTrace();
            response.getWriter().println("Error: " + e.getMessage());
        }
    }
}
